[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[functions."openai-assistant"]
  timeout = 300

[dev]
  framework = "vite"
  targetPort = 5173

# Security: Force HTTPS redirect
[[redirects]]
  from = "http://medimindexpert.netlify.app/*"
  to = "https://medimindexpert.netlify.app/:splat"
  status = 301
  force = true

# Podcast functionality migrated to Supabase Edge Functions

# Specific API routes first (order matters)
[[redirects]]
  from = "/api/flowise/chat"
  to = "/.netlify/functions/flowise-fixed"
  status = 200
  force = true

[[redirects]]
  from = "/api/flowise/auth"
  to = "/.netlify/functions/flowise-auth"
  status = 200
  force = true

[[redirects]]
  from = "/api/test-auth"
  to = "/.netlify/functions/test-auth"
  status = 200
  force = true

# Handle OPTIONS requests for CORS preflight (must be after specific routes)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/cors-handler"
  status = 200
  force = true
  conditions = {Methods = ["OPTIONS"]}

[[redirects]]
  from = "/api/openai-assistant"
  to = "/.netlify/functions/openai-assistant"
  status = 200
  force = true

[[redirects]]
  from = "/api/test-openai-auth"
  to = "/.netlify/functions/test-openai-auth"
  status = 200
  force = true

[[redirects]]
  from = "/api/exa/search"
  to = "/.netlify/functions/exa-search"
  status = 200
  force = true

[[redirects]]
  from = "/api/perplexity/chat/completions"
  to = "/.netlify/functions/perplexity-chat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# API Security Headers
[[headers]]
  for = "/api/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true# Updated: Thu Jul  3 00:37:46 +04 2025
